### ISSUE TITLE
Capture page number

### ISSUE THREAD

**Issue by heiders** [Edo78/obsidian-koreader-sync#22]
I would like to see the page number associated with the note/highlight for easy reference If I want to return to the original text.

I guess KOReader does somehow capture it since this standalone utility seems to be able to capture the page number: https://www.mobileread.com/forums/showthread.php?t=265433

**Comment by Edo78** [comment]
I'll have to double check.
I'm pretty sure I haven't seen a property for the page number but the whole koreader file is IMO a bit of a mess.

If someone can do it then I should be able to do it as well but don't hold your breath
