### ISSUE TITLE
Book Progress

### ISSUE THREAD

**Issue by javiavid** [Edo78/obsidian-koreader-sync#41]
Hi Edo, maybe it would be interesting to extract the progress of the book and put it in the general note of the book (the one with the dataview query).
This with the latest minimal options would be very good to have a database of books.

https://github.com/kepano/obsidian-minimal/releases/tag/4.4.5

![image](https://user-images.githubusercontent.com/7627504/151762324-ede0ee61-8fb6-46a4-9405-928a1e6f2e64.png)

**Comment by Edo78** [comment]
Somewhere in KOReader the progress is surely there ... I just have to check where it is.

**Comment by javiavid** [comment]
Yes, with this calibre plugin it is possible to extract it. Maybe it's easy.
https://www.mobileread.com/forums/showthread.php?t=334977

**Comment by Edo78** [comment]
I just checked and it's _super easy barely an inconvenience_ (cit.)
I'd like to release with #33 so that user can create their template even for those notes but I think it's "safer" if I release this in bundle with #42 and #43

**Comment by Edo78** [comment]
The next release will require more work but everithing is connected so a partial release will be bad for future updates.
https://github.com/Edo78/obsidian-koreader-sync/milestone/5

**Comment by javiavid** [comment]
I think it's perfect that you're grouping it together.

**Comment by Edo78** [comment]
You're welcome. I'm still working on other issues but they are more complex than originally anticipated so I create a release with the available code to let you enjoy it :+1:
