### ISSUE TITLE
All the highlights from a book in a single file?

### ISSUE THREAD

**Issue by jeffvogelsang** [Edo78/obsidian-koreader-sync#56]
Hi -- Would it be possible to have a mode that has all the highlights from a book in a single note file, similar to how the Readwise plugins work?

**Comment by Edo78** [comment]
Hi, sorry but I've already looked into that (#9 and #55) but to achieve that I'll have to sacrifice a lot of features.
The official workaround is to [configure a book view](https://github.com/Edo78/obsidian-koreader-sync#book-view-configuration) through Dataview so you can have a view for each book grouping all the notes.
