### ISSUE TITLE
Folder with each book

### ISSUE THREAD

**Issue by javiavid** [Edo78/obsidian-koreader-sync#7]
For it to be more organized, it would be good to be able to have the option that each book creates a folder and within all of its annotations.

**Comment by Edo78** [comment]
I'm not a big fan of folders use but I surely see you point and it should be fairly easy to implement.
Just wondering if you prefer the note rappresenting the book itself in the "root" koreader folder on in the book subfolder.
Maybe I'll use another setting to let user decide.
