### ISSUE TITLE
Custom Template

### ISSUE THREAD

**Issue by javiavid** [Edo78/obsidian-koreader-sync#8]
It would be great to be able to create a template for the notes, something similar to what the Hypothesis plugin does.
In this way you could do the plugin compatible with DataView.

**Comment by Edo78** [comment]
I'd have to check that plugin.
I was thinking about letting the user create a template for its note but I'm not sure about the best way to do it (and I don't like to have the user to delete their notes to have them recreated as I improve my plugin.

Definitely on my TODO

**Comment by javiavid** [comment]
Thanks!

**Comment by Edo78** [comment]
It was very easy.

BTW I added some examples in the README to show how to use Dataview even withou a custom template thanks to frontmatter
